FROM node:16-alpine
WORKDIR /user/src/app
COPY . .

RUN npm install
RUN npm run build

FROM nginx:1.14-alpine
COPY nginx.conf /etc/nginx/nginx.conf

RUN apk add bash

COPY ./scripts /scripts

COPY --from=0 /user/src/app/dist /usr/share/nginx/html

CMD ["/scripts/start.sh"]

